version: "3.9"
services:
  db:
    container_name: "my_db"
    build:
      context: .
      dockerfile: Dockerfile_postgresql
    env_file:
      - ".env"
    ports:
      - "${POSTGRES_PORT}:${POSTGRES_PORT}"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 10s
  backend:
    container_name: "my_app"
    build:
      context: .
      dockerfile: Dockerfile
    depends_on:
      db:
        condition: service_healthy
